import os
import sys

pkg_config_cmd = "pkg-config"
srvliblist = ['glib-2.0', 'uv']
liblist = ['glib-2.0', 'ncurses']
cflags = '-I/usr/local/include'
linkflags = '-L/usr/local/lib'

ntetris_cfiles = ['tetris.c', ]
ntetris_srv_files = ['tetris_serv.c', 'packet.c', 'player.c', 'rand.c', 'room.c', 'cmd.c', 'server.c', 'game.c']

if sys.platform == "darwin":
   pkg_config_cmd = '/opt/local/bin/pkg-config'

if 'linux' in sys.platform:
  liblist.append('bsd')
  srvliblist.append('bsd')
  cflags += ' -std=gnu99 -O3'

if 'sunos' in sys.platform:
  cflags = ' '.join((cflags, '-m64', '-I/usr/include/ncurses', '-features=extensions,typeof', '-xc99', '-xmemalign=1s', '-xO5'))
  ntetris_cfiles.append('strtonum.c')
  ntetris_srv_files.append('strtonum.c')
  srvliblist.extend(['socket', 'mtmalloc'])
  linkflags = ' '.join(('-m64', '-L/usr/lib/64')) 

env = Environment(ENV = os.environ)
env.ParseConfig(pkg_config_cmd + ' --cflags --libs glib-2.0')

env.Program('ntetris', ntetris_cfiles, LIBS=liblist, CFLAGS=cflags, LINKFLAGS=linkflags)
env.Program('ntetris_srv', ntetris_srv_files, LIBS=srvliblist, CFLAGS=cflags, LINKFLAGS=linkflags)

